$ARCH_TO_FOLDER_MAP = @{
    "i686-pc-windows-msvc"    = "x86"
    "x86_64-pc-windows-msvc"  = "x64"
    "aarch64-pc-windows-msvc" = "arm64"
}

$FILES = @(
    "AdGuardFLM.dll",
    "AdGuardFLM.pdb"
)

$CONFIGS = @(
    "Release",
    "Debug"
)

$global:win_root = "crates\ffi\src\platforms\windows";

Function CopyToTestsBuildFolder {
    Write-Output "Copying files...";
    foreach ($arch in $ARCH_TO_FOLDER_MAP.Keys) {
        foreach ($file in $FILES) {     
            $folder = $ARCH_TO_FOLDER_MAP[$arch]
            $srcPath = "target\$arch\release\$file"

            foreach ($config in $CONFIGS) {
                $destPath = "$win_root\build\bin\$config\$folder\$file"
            
                $destDir = Split-Path -Path $destPath -Parent
                if (!(Test-Path -Path $destDir)) {
                    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
                }
            
                Copy-Item -Path $srcPath -Destination $destPath
                if (!$?) {
                    Write-Error "Failed to copy file from $srcPath to $destPath"
                    exit 1
                }
            
                Write-Output "Copied: $srcPath to: $destPath"
            }
        }
    }

    Write-Output "Copying files has been completed successfully";
}

Function RenameOutFile {
    param([string]$profile_name)
    Move-Item -Path "target\$profile_name\release\filter_list_manager_ffi.dll" -Destination "target\$profile_name\release\AdGuardFLM.dll" -Force
    Move-Item -Path "target\$profile_name\release\filter_list_manager_ffi.pdb" -Destination "target\$profile_name\release\AdGuardFLM.pdb" -Force
}

Function ResolveVersion {
    # Resolves the version: the FLM_VERSION env var, else `git describe` over
    # v* tags. A leading 'v' is stripped. Same rule as the crates' build.rs.
    $version = $env:FLM_VERSION
    if ([string]::IsNullOrWhiteSpace($version)) {
        $version = (& git describe --tags "--match=v*" --abbrev=0 2>$null)
        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($version)) {
            throw "Cannot resolve version: set FLM_VERSION or create a v* git tag"
        }
    }

    return $version.Trim().TrimStart('v')
}

# Generates C# code from Protobuf definitions
Function GenerateProtobufBindings {
    Write-Output "Generating Protobuf bindings..."
        
    $protosDir = Join-Path $PSScriptRoot "..\..\..\protobuf" | Resolve-Path
    
    # Output directory for generated C# files
    $outputDir = "$win_root\AdGuard.FilterListManager\ProtobufGenerated"
    
    # Create output directory if it doesn't exist
    if (-not (Test-Path $outputDir)) {
        New-Item -ItemType Directory -Force -Path $outputDir
    }
    
    # Check if protoc is installed
    try {
        $protocVersion = (& protoc --version)
        Write-Output "Using protoc version: $protocVersion"
    }
    catch {
        Write-Error "protoc is not installed or not in PATH. Please install Protocol Buffers compiler."
        exit 1
    }

    protoc --csharp_out="$outputDir" -I="$protosDir" filters.proto flm_interface.proto misc_models.proto configuration.proto outer_error.proto
    
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Failed to generate Protobuf bindings for $protoFile"
        exit 1
    }
    
    Write-Output "Protobuf bindings generated successfully"
}

Function SetMetadataVersion {
    # Generates metadata.json with the FFI crate version (adguard-flm-ffi)
    # alongside the nuspec, so it can be packed into the NuGet.
    $ffiVersion = ResolveVersion
    $buildDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    $metadata = [ordered]@{
        adguard_flm_ffi_version = $ffiVersion
        build_date              = $buildDate
    }

    $metadataPath = "$win_root\AdGuard.FilterListManager\metadata.json"
    $json = $metadata | ConvertTo-Json
    $utf8NoBom = New-Object System.Text.UTF8Encoding $False
    [System.IO.File]::WriteAllText($metadataPath, $json, $utf8NoBom)
    Write-Host "metadata.json generated at $metadataPath with FFI version $ffiVersion"
}

Function RustBuild {    
    try {
        # The native .dll version (AGWinFLM.rc) is generated by the ffi build.rs,
        # and the C# adapter <Version> by Directory.Build.targets. Here we only
        # emit metadata.json.
        SetMetadataVersion;
    }
    catch {
        Write-Host $_
        exit 1;
    }

    $env:RUSTFLAGS = "-Ctarget-feature=+crt-static";

    Write-Output "Start executing method RustBuild";
    & cargo build --release --lib --package adguard-flm-ffi --target i686-pc-windows-msvc --features rusqlite-bundled,win-res --locked
    RenameOutFile "i686-pc-windows-msvc"
    & cargo build --release --lib --package adguard-flm-ffi --target x86_64-pc-windows-msvc --features rusqlite-bundled,win-res --locked
    RenameOutFile "x86_64-pc-windows-msvc"
    & cargo build --release --lib --package adguard-flm-ffi --target aarch64-pc-windows-msvc --features rusqlite-bundled,win-res --locked
    RenameOutFile "aarch64-pc-windows-msvc"

    # Generate Protobuf bindings
    GenerateProtobufBindings;

    CopyToTestsBuildFolder;
    Write-Output "Executing method RustBuild has been completed successfully";
}