namespace AdGuard.FilterListManagerProtobuf.RustInterface
{
    internal enum FfiMethod
    {
        InstallCustomFilterList,
        EnableFilterLists,
        InstallFilterLists,
        DeleteCustomFilterLists,
        GetFullFilterListById,
        GetStoredFiltersMetadata,
        GetStoredFilterMetadataById,
        SaveCustomFilterRules,
        SaveDisabledRules,
        UpdateFilters,
        ForceUpdateFiltersByIds,
        FetchFilterListMetadata,
        LiftUpDatabase,
        GetAllTags,
        GetAllGroups,
        ChangeLocale,
        PullMetadata,
        UpdateCustomFilterMetadata,
        GetDatabasePath,
        GetDatabaseVersion,
        InstallCustomFilterFromString,
        GetActiveRules,
        GetFilterRulesAsStrings,
        SaveRulesToFileBlob,
        GetDisabledRules,
        SetProxyMode
    }
}
