---
version: 2
plan:
  project-key: CL
  key: FAL
  name: Filter List Manager - Android library
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  docker:
    image: adguard/core-libs:2.5
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
    docker-run-arguments: []
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        cd crates/ffi/src/platforms/android
        cat > lib/publishing.gradle.kts << EOF
        //// This script should be applied to a project that already has the maven-publish plugin applied
        //// It configures the publishing repositories for the project
        import org.gradle.api.publish.PublishingExtension

        (project.extensions.findByName("publishing") as? PublishingExtension)?.apply {
            repositories {
                maven {
                    name = "adguard"
                    url = uri("https://art.int.agrd.dev/artifactory/adguard-maven")
                    credentials {
                        username = "${bamboo.artifactoryUser}"
                        password = "${bamboo.artifactoryPassword}"
                    }
                }
            }
        }
        EOF

        echo cmake.dir=$(dirname $(dirname $(which cmake))) >> local.properties

        ./gradlew assembleRelease
        if [ "${bamboo.repository.branch.name}" == "master" ]; then
            ./gradlew publish
        fi
  requirements:
  - adg-privileged-docker
  artifact-subscriptions: []
repositories:
- core-libs/filter-list-manager:
    scope: global
triggers: []
branches:
  create: manually
  delete:
    after-deleted-days: 7
    after-inactive-days: never
  integration:
    push-on-success: false
    merge-from: Filter List Manager - Android library
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
