---
version: 2

plan:
  project-key: CL
  key: FLMIV
  name: Filter List Manager - Increment version

variables:
  ffi.custom.version: 'none'
  adguard.flm.custom.version: 'none'

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: JOB1
  docker:
    image: adguard/core-libs:2.8
    docker-run-arguments: []
  tasks:
    - !include 'docker-clean.yaml'
    - checkout:
        force-clean-build: 'true'
        description: Checkout Default Repository
    - checkout:
        repository: git-scripts
        path: git-scripts
    - script:
        interpreter: SHELL
        scripts:
          - |-
            ./bamboo-specs/scripts/increment_version.sh
        description: Increment version
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]

repositories:
  - core-libs/filter-list-manager:
      scope: global
  - git-scripts:
      scope: global

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: [ ]
labels: [ ]

other:
  concurrent-build-plugin: system-default
