---
version: 2
branches:
  create: manually
plan:
  project-key: WIN
  key: BFLMW
  name: Build Filter List Manager Windows
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'true'
      description: Checkout main repository
  - checkout:
      description: Checkout private repository
      repository: adguard-windows-private
      path: ${bamboo.private_repo_path}
      force-clean-build: 'true'
  - script:
      description: Checkout private repository hash
      interpreter: WINDOWS_POWER_SHELL
      scripts:
      - |-
        . "${bamboo.private_repo_path}/PowerShellScripts/product_version.ps1"
        CheckoutHash "${bamboo.private_repo_hash}" "$Env:bamboo_working_directory/${bamboo.private_repo_path}"
  - script:
      interpreter: WINDOWS_POWER_SHELL
      description: Prepare environment
      scripts:
      - |-
        . "${bamboo.private_repo_path}/PowerShellScripts/build_product.ps1"
        PrepareEnvironment "${bamboo.nuget_repo_url}"
  - script:
      interpreter: WINDOWS_POWER_SHELL
      description: Set first project to update
      scripts:
      - |-
        . "${bamboo.deploy_script}"
        SetRootFolder "${bamboo.root_folder}"
        UpSchemaIfNeeded "AdGuard.FilterListManager\AdGuard.FilterListManager.schema.json"
        InitializeProjects
        SetFirstProjectToUpdate   
  - inject-variables:
      file: project_to_update.txt
      scope: LOCAL
      namespace: common     
  - script:
      interpreter: WINDOWS_POWER_SHELL
      description: Main build
      scripts:
      - |-

        . "${bamboo.deploy_script}"
        VersionIncrement "${Env:bamboo_planRepository_repositoryUrl}";
        
        . "${bamboo.root_folder}\Scripts\build_adapter.ps1"
        RustBuild
      
        . "${bamboo.deploy_script}"
        MainBuild "${bamboo.build_configuration}" "${bamboo.define_constants}" "${bamboo.build_folder}";
      environment: channel="${bamboo.channel}" "use_force_master="${bamboo.use_force_master}"
  - script:
      interpreter: WINDOWS_POWER_SHELL
      description: Run unit tests
      scripts:
      - |-
        . "${bamboo.deploy_script}"
        RunUnitTests "${bamboo.build_platform}" "${bamboo.build_configuration}" "${bamboo.build_folder}"
  - script:
      interpreter: WINDOWS_POWER_SHELL
      description: Main deploy
      scripts:
      - |-
        . "${bamboo.deploy_script}";
        MainDeploy "${bamboo.build_folder}" "$Env:bamboo_windowsCertStoragePassword" ${bamboo.skip_signing_libs} "$Env:bamboo_artifactoryUser" "$Env:bamboo_artifactoryPassword";
      environment: use_force_master="${bamboo.use_force_master}"   
  artifacts:
  - name: dll
    pattern: '*.dll'
    shared: true
    required: true
  - name: nupkg
    pattern: '*.nupkg'
    shared: true
    required: true
  requirements:
  - ephemeral-windows
  - image: registry.int.agrd.dev/windows/windows11-bamboo:20
  final-tasks:
  - any-task:
      plugin-key: com.atlassian.bamboo.plugin.dotnet:nunit
      configuration:
        testResultsDirectory: '**/TestResults.xml'
        pickupOutdatedFiles: 'false'
variables:
  build_configuration: Release
  build_folder: crates\ffi\src\platforms\windows\build\bin\Release
  build_platform: AnyCPU
  channel: release
  code_coverage_threshold_percent: '1'
  define_constants: BUILD=Release
  use_force_master: 'false'
  private_repo_path: crates/ffi/src/platforms/windows/adguard-windows-private
  nuget_repo_url: https://art.int.agrd.dev/artifactory/api/nuget/adguard-nuget
  deploy_script: crates\ffi\src\platforms\windows\adguard-windows-private\bamboo-specs\main_deploy.ps1
  # opencover: opencover.xml
  root_folder: crates/ffi/src/platforms/windows
  skip_signing_libs: $False
  private_repo_hash: head
notifications: []
labels: []
triggers: []
other:
  concurrent-build-plugin: system-default
