// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: configuration.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum FilterListManager_FilterListType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case standard // = 0
  case dns // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .standard
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .standard
    case 1: self = .dns
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .standard: return 0
    case .dns: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [FilterListManager_FilterListType] = [
    .standard,
    .dns,
  ]

}

/// FLM Requests proxy mode
public enum FilterListManager_RawRequestProxyMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// System proxy will be used
  case useSystemProxy // = 0

  /// All proxies disabled
  case noProxy // = 1

  /// Use custom proxy
  case useCustomProxy // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .useSystemProxy
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .useSystemProxy
    case 1: self = .noProxy
    case 2: self = .useCustomProxy
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .useSystemProxy: return 0
    case .noProxy: return 1
    case .useCustomProxy: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [FilterListManager_RawRequestProxyMode] = [
    .useSystemProxy,
    .noProxy,
    .useCustomProxy,
  ]

}

public struct FilterListManager_FiltersCompilationPolicy: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of literal constants for filters conditional compilation.
  public var constants: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct FilterListManager_Configuration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var filterListType: FilterListManager_FilterListType = .standard

  /// Absolute path for library working directory.
  /// This will be used for database operating.
  /// If value is "None", `cwd` will be used.
  public var workingDirectory: String {
    get {return _workingDirectory ?? String()}
    set {_workingDirectory = newValue}
  }
  /// Returns true if `workingDirectory` has been explicitly set.
  public var hasWorkingDirectory: Bool {return self._workingDirectory != nil}
  /// Clears the value of `workingDirectory`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingDirectory() {self._workingDirectory = nil}

  /// Locale that needs to be used to extract localized names and descriptions.
  /// Locale `en-GB` will be normalized to internal `en_GB` representation.
  /// Default value: en.
  public var locale: String = String()

  /// Default period for expires in seconds (unless specified in "Expires", or its value is too small).
  /// Default value: 86400 (1 day).
  /// Values < 3600 will be clamped to 3600.
  public var defaultFilterListExpiresPeriodSec: Int32 = 0

  /// Settings for filters compilation or collection from compiled parts.
  /// 
  /// ### Compilation
  /// During the update, each filter will be "compiled" into main filter and its includes.
  /// Main filter remains unchanged. But in includes, (include, if/else/endif) directives will be resolved, using this policy. 
  /// Recursive includes will be inlined.
  /// 
  /// ### Collection
  /// When you get filters, they will be collected from compiled parts (main filter + includes).
  /// All directives in main filter will be resolved, using this policy, and includes will be injected. 
  public var filtersCompilationPolicy: FilterListManager_FiltersCompilationPolicy {
    get {return _filtersCompilationPolicy ?? FilterListManager_FiltersCompilationPolicy()}
    set {_filtersCompilationPolicy = newValue}
  }
  /// Returns true if `filtersCompilationPolicy` has been explicitly set.
  public var hasFiltersCompilationPolicy: Bool {return self._filtersCompilationPolicy != nil}
  /// Clears the value of `filtersCompilationPolicy`. Subsequent reads from it will return its default value.
  public mutating func clearFiltersCompilationPolicy() {self._filtersCompilationPolicy = nil}

  /// URL of the index (filters.json) file.
  public var metadataURL: String = String()

  /// URL of the locales (filters_i18n.json) file.
  public var metadataLocalesURL: String = String()

  /// Requests timeouts in milliseconds. Default value 60000 (60 seconds).
  public var requestTimeoutMs: Int32 = 0

  /// “Uplifting” a database is a set of measures that brings the database up to date:
  public var autoLiftUpDatabase: Bool = false

  /// Proxy mode
  public var requestProxyMode: FilterListManager_RawRequestProxyMode = .useSystemProxy

  /// Custom proxy addr for requests
  public var requestCustomProxyAddr: String = String()

  /// Client app name
  public var appName: String = String()

  /// Client app version
  public var version: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _workingDirectory: String? = nil
  fileprivate var _filtersCompilationPolicy: FilterListManager_FiltersCompilationPolicy? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "filter_list_manager"

extension FilterListManager_FilterListType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "STANDARD"),
    1: .same(proto: "DNS"),
  ]
}

extension FilterListManager_RawRequestProxyMode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "USE_SYSTEM_PROXY"),
    1: .same(proto: "NO_PROXY"),
    2: .same(proto: "USE_CUSTOM_PROXY"),
  ]
}

extension FilterListManager_FiltersCompilationPolicy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FiltersCompilationPolicy"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "constants"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.constants) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.constants.isEmpty {
      try visitor.visitRepeatedStringField(value: self.constants, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FilterListManager_FiltersCompilationPolicy, rhs: FilterListManager_FiltersCompilationPolicy) -> Bool {
    if lhs.constants != rhs.constants {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FilterListManager_Configuration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Configuration"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "filter_list_type"),
    2: .standard(proto: "working_directory"),
    3: .same(proto: "locale"),
    4: .standard(proto: "default_filter_list_expires_period_sec"),
    5: .standard(proto: "filters_compilation_policy"),
    6: .standard(proto: "metadata_url"),
    7: .standard(proto: "metadata_locales_url"),
    8: .standard(proto: "request_timeout_ms"),
    9: .standard(proto: "auto_lift_up_database"),
    10: .standard(proto: "request_proxy_mode"),
    11: .standard(proto: "request_custom_proxy_addr"),
    12: .standard(proto: "app_name"),
    13: .same(proto: "version"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.filterListType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._workingDirectory) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.locale) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.defaultFilterListExpiresPeriodSec) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._filtersCompilationPolicy) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.metadataURL) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.metadataLocalesURL) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.requestTimeoutMs) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.autoLiftUpDatabase) }()
      case 10: try { try decoder.decodeSingularEnumField(value: &self.requestProxyMode) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.requestCustomProxyAddr) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.appName) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.filterListType != .standard {
      try visitor.visitSingularEnumField(value: self.filterListType, fieldNumber: 1)
    }
    try { if let v = self._workingDirectory {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.locale.isEmpty {
      try visitor.visitSingularStringField(value: self.locale, fieldNumber: 3)
    }
    if self.defaultFilterListExpiresPeriodSec != 0 {
      try visitor.visitSingularInt32Field(value: self.defaultFilterListExpiresPeriodSec, fieldNumber: 4)
    }
    try { if let v = self._filtersCompilationPolicy {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.metadataURL.isEmpty {
      try visitor.visitSingularStringField(value: self.metadataURL, fieldNumber: 6)
    }
    if !self.metadataLocalesURL.isEmpty {
      try visitor.visitSingularStringField(value: self.metadataLocalesURL, fieldNumber: 7)
    }
    if self.requestTimeoutMs != 0 {
      try visitor.visitSingularInt32Field(value: self.requestTimeoutMs, fieldNumber: 8)
    }
    if self.autoLiftUpDatabase != false {
      try visitor.visitSingularBoolField(value: self.autoLiftUpDatabase, fieldNumber: 9)
    }
    if self.requestProxyMode != .useSystemProxy {
      try visitor.visitSingularEnumField(value: self.requestProxyMode, fieldNumber: 10)
    }
    if !self.requestCustomProxyAddr.isEmpty {
      try visitor.visitSingularStringField(value: self.requestCustomProxyAddr, fieldNumber: 11)
    }
    if !self.appName.isEmpty {
      try visitor.visitSingularStringField(value: self.appName, fieldNumber: 12)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FilterListManager_Configuration, rhs: FilterListManager_Configuration) -> Bool {
    if lhs.filterListType != rhs.filterListType {return false}
    if lhs._workingDirectory != rhs._workingDirectory {return false}
    if lhs.locale != rhs.locale {return false}
    if lhs.defaultFilterListExpiresPeriodSec != rhs.defaultFilterListExpiresPeriodSec {return false}
    if lhs._filtersCompilationPolicy != rhs._filtersCompilationPolicy {return false}
    if lhs.metadataURL != rhs.metadataURL {return false}
    if lhs.metadataLocalesURL != rhs.metadataLocalesURL {return false}
    if lhs.requestTimeoutMs != rhs.requestTimeoutMs {return false}
    if lhs.autoLiftUpDatabase != rhs.autoLiftUpDatabase {return false}
    if lhs.requestProxyMode != rhs.requestProxyMode {return false}
    if lhs.requestCustomProxyAddr != rhs.requestCustomProxyAddr {return false}
    if lhs.appName != rhs.appName {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
