name: Testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cargo-check:
    name: Cargo check
    runs-on: [team-corelibs]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Format, lint and test
        uses: AdGuardSoftwareLimited/actions/actions/cargo@master
        with:
          run: |
            cargo fmt --all -- --check
            cargo clippy --locked
            cargo test --workspace --lib --all-features --locked
