name: Testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-fixme:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/check-fixme.yml@master
    with:
      team: corelibs
